INSERT INTO Data (ID, Name, Age) VALUES (Page d'exportation PDF, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Table des matières, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Page n° : 2, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (1 achete, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Page n° : 3, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (2 appartient, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Page n° : 4, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (3 boisson, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Page n° : 5, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (4 client, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Page n° : 6, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (5 comprend, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Page n° : 7, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (6 contient, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Page n° : 8, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (7 est constitue, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Page n° : 9, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (8 focaccia, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Page n° : 10, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (9 ingredient, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Page n° : 11, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (10 marque, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Page n° : 12, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (11 menu, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Page n° : 13, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (12 Schéma relationnel, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Page n° : 1/13, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (mar. 10 juin 2025 à 06:54, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Page d'exportation PDF, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (1 achete, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Création : dim. 08 juin 2025 à 17:09, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Colonne, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Type, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Attributs, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Null, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Valeur par défaut, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Extra, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Est relié à, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Commentaires, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (MIME, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (id_date, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (date, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Non, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (current_tim, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (estamp(), 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Page n° : 2/13, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (mar. 10 juin 2025 à 06:54, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Page d'exportation PDF, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (2 appartient, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Création : dim. 08 juin 2025 à 07:24, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Colonne, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Type, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Attributs, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Null, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Valeur par défaut, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Extra, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Est relié à, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Commentaires, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (MIME, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (id_appartient, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (int(11), 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Non, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (-> marque.id_marque, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (ON UPDATE RESTRICT, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (ON DELETE RESTRICT, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Page n° : 3/13, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (mar. 10 juin 2025 à 06:54, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Page d'exportation PDF, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (3 boisson, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Création : dim. 08 juin 2025 à 08:15, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Colonne, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Type, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Attributs, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Null, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Valeur par défaut, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Extra, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Est relié à, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Commentaires, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (MIME, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (id_boisson, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (int(11), 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Non, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (auto_increment, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (nom_boisson, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (varchar(50), 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Oui, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (NULL, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (marque, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (varchar(50), 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Non, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Page n° : 4/13, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (mar. 10 juin 2025 à 06:54, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Page d'exportation PDF, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (4 client, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Création : dim. 08 juin 2025 à 07:42, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Colonne, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Type, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Attributs, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Null, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Valeur par défaut, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Extra, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Est relié à, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Commentaires, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (MIME, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (id_client, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (int(11), 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Non, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (auto_increment, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (nom, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (varchar(50), 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Non, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (email, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (varchar(150, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (), 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Non, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (code_postale, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (int(11), 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Non, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Page n° : 5/13, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (mar. 10 juin 2025 à 06:54, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Page d'exportation PDF, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (5 comprend, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Création : dim. 08 juin 2025 à 16:19, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Colonne, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Type, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Attributs, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Null, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Valeur par défaut, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Extra, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Est relié à, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Commentaires, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (MIME, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (idquantite, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (int(11), 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Non, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (-> ingredient.id_ingredient, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (ON UPDATE RESTRICT, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (ON DELETE RESTRICT, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Page n° : 6/13, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (mar. 10 juin 2025 à 06:54, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Page d'exportation PDF, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (6 contient, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Création : dim. 08 juin 2025 à 07:25, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Colonne, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Type, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Attributs, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Null, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Valeur par défaut, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Extra, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Est relié à, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Commentaires, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (MIME, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (id_contient, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (int(11), 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Non, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (-> menu.id_menu, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (ON UPDATE RESTRICT, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (ON DELETE RESTRICT, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Page n° : 7/13, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (mar. 10 juin 2025 à 06:54, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Page d'exportation PDF, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (7 est constitue, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Création : dim. 08 juin 2025 à 16:59, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Colonne, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Type, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Attributs, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Null, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Valeur par défaut, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Extra, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Est relié à, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Commentaires, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (MIME, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (id_constitue, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (int(11), 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Non, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (-> menu.id_menu, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (ON UPDATE RESTRICT, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (ON DELETE RESTRICT, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Page n° : 8/13, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (mar. 10 juin 2025 à 06:54, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Page d'exportation PDF, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (8 focaccia, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Création : dim. 08 juin 2025 à 16:58, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Colonne, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Type, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Attributs, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Null, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Valeur par défaut, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Extra, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Est relié à, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Commentaires, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (MIME, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (id_focaccia, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (int(11), 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Non, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (auto_increment, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (nom_focaccia, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (varchar(255, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (), 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Oui, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (NULL, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (prix, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (decimal(5, '2)', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Oui, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (NULL, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (ingredient, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (varchar(255, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (), 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Non, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Page n° : 9/13, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (mar. 10 juin 2025 à 06:54, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Page d'exportation PDF, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (9 ingredient, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Création : dim. 08 juin 2025 à 07:11, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Colonne, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Type, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Attributs, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Null, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Valeur par défaut, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Extra, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Est relié à, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Commentaires, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (MIME, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (id_ingredient, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (int(11), 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Non, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (auto_increment, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (nom, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (varchar(100, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (), 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Non, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Page n° : 10/13, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (mar. 10 juin 2025 à 06:54, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Page d'exportation PDF, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (10 marque, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Création : dim. 08 juin 2025 à 07:15, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Colonne, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Type, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Attributs, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Null, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Valeur par défaut, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Extra, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Est relié à, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Commentaires, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (MIME, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (id_marque, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (int(11), 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Non, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (auto_increment, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (nom, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (varchar(50), 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Non, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Page n° : 11/13, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (mar. 10 juin 2025 à 06:54, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Page d'exportation PDF, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (11 menu, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Création : dim. 08 juin 2025 à 09:17, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Colonne, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Type, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Attributs, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Null, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Valeur par défaut, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Extra, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Est relié à, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Commentaires, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (MIME, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (id_menu, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (int(11), 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Non, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (auto_increment, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (nom, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (varchar(50), 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Non, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (prix, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (decimal(5, '2)', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Non, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Page n° : 12/13, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (mar. 10 juin 2025 à 06:54, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Page d'exportation PDF, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( achete, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( id_date, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( appartient, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( id_appartient, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( boisson, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( id_boisson, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( nom_boisson, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( marque, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( client, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( id_client, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( nom, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( email, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( code_postale, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( comprend, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( idquantite, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( contient, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( id_contient, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( est constitue, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( id_constitue, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( focaccia, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( id_focaccia, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( nom_focaccia, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( prix, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( ingredient, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( ingredient, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( id_ingredient, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( nom, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( marque, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( id_marque, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( nom, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( menu, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( id_menu, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( nom, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( prix, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Powered by TCPDF (www.tcpdf.org), 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Page n° : 13/13, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (mar. 10 juin 2025 à 06:54, 'undefined', undefined);